language: java

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2/repository

before_install:
  - sudo apt update
  - sudo apt install openjfx
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export PROJECT_VERSION=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

install: skip

script: mvn install -Dgpg.skip=true --batch-mode --show-version --update-snapshots
